class GenericBluetoothEarphones {
        static String brandName = "Generics";
        static String modelNumber = "BOGHMXT";
        static String itemType = "Wireless Earphones";
        static String ageRange = "Adult";
        static String countryOfOrigin = "Indian";
        static String manufacturer = "VAGHANI";
        static String audioDriverType = "Dynamic";
        static String productFeatures = "Noise Cancellation,Touch Control";
        static String enclosureMaterial = "Plastic";
        static String specificUses = "Music";
        static String compatibleDevices = "Cellphones, Tablets";
        static String waterResistance = "Non-Water Resistant";
        static String connectivity = "Wireless";
        static String wirelessTechnology = "Wireless";
        static String bluetoothVersion = "5.0";
        static String bluetoothRange = "8 Metres";
        static int batteryChargeTimeMinutes = 8;
        static int batteryLifeHours = 6;
        static String asin = "BOGHMXTDCW";

    public static void main(String[] args) {

        String brandName = "Generic";
        String modelNumber = "BOGHMXT";
        String itemType = "In-Ear Wireless Earphones";
        String ageRange = "Teen, Adult";
        String countryOfOrigin = "India";
        String manufacturer = "VAGHANI ENTERPRISES";
        String audioDriverType = "Dynamic Driver";
        String productFeatures = "Noise Cancellation, Sweatproof, Touch Control";
        String enclosureMaterial = "Plastic";
        String specificUses = "Music, Gaming";
        String compatibleDevices = "Cellphones, Tablets, Laptops, Desktops";
        String waterResistance = "Water Resistant";
        String connectivity = "Wireless";
        String wirelessTechnology = "Bluetooth";
        String bluetoothVersion = "5.1";
        String bluetoothRange = "10 Metres";
        int batteryChargeTimeMinutes = 10;
        int batteryLifeHours = 7;
        String asin = "BOGHMXTDCW";

        System.out.println("Brand Name: " + brandName);
        System.out.println("Brand Name: " + GenericBluetoothEarphones.brandName);
        System.out.println("Brand Name: " + brandName);
        System.out.println("Brand Name: " + GenericBluetoothEarphones.brandName);
        System.out.println("Item Type: " + itemType);
        System.out.println("Item Type: " + GenericBluetoothEarphones.itemType);
        System.out.println("Age Range: " + ageRange);
        System.out.println("Age Range: " + GenericBluetoothEarphones.ageRange);
        System.out.println("Country Of Origin: " + countryOfOrigin);
        System.out.println("Country Of Origin: " + GenericBluetoothEarphones.countryOfOrigin);
        System.out.println("Manufacturer: " + manufacturer);
        System.out.println("Manufacturer: " + GenericBluetoothEarphones.manufacturer);
        System.out.println("Audio Driver Type: " + audioDriverType);
        System.out.println("Audio Driver Type: " + GenericBluetoothEarphones.audioDriverType);
        System.out.println("Product Features: " + productFeatures);
        System.out.println("Product Features: " + GenericBluetoothEarphones.productFeatures);
        System.out.println("Enclosure Material: " + enclosureMaterial);
        System.out.println("Enclosure Material: " + GenericBluetoothEarphones.enclosureMaterial);
        System.out.println("Specific Uses: " + specificUses);
        System.out.println("Specific Uses: " + GenericBluetoothEarphones.specificUses);
        System.out.println("Compatible Devices: " + compatibleDevices);
        System.out.println("Compatible Devices: " + GenericBluetoothEarphones.compatibleDevices);
        System.out.println("Water Resistance: " + waterResistance);
        System.out.println("Water Resistance: " + GenericBluetoothEarphones.waterResistance);
        System.out.println("Connectivity: " + connectivity);
        System.out.println("Connectivity: " + GenericBluetoothEarphones.connectivity);
        System.out.println("Wireless Technology: " + wirelessTechnology);
        System.out.println("Wireless Technology: " + GenericBluetoothEarphones.wirelessTechnology);
        System.out.println("Bluetooth Version: " + bluetoothVersion);
        System.out.println("Bluetooth Version: " + GenericBluetoothEarphones.bluetoothVersion);
        System.out.println("Bluetooth Range: " + bluetoothRange);
        System.out.println("Bluetooth Range: " + GenericBluetoothEarphones.bluetoothRange);
        System.out.println("Battery Charge Time (Minutes): " + batteryChargeTimeMinutes);
        System.out.println("Battery Charge Time (Minutes): " + GenericBluetoothEarphones.batteryChargeTimeMinutes);
        System.out.println("Battery Life (Hours): " + batteryLifeHours);
        System.out.println("Battery Life (Hours): " + GenericBluetoothEarphones.batteryLifeHours);
        System.out.println("ASIN: " + asin);
        System.out.println("ASIN: " + GenericBluetoothEarphones.asin);
    }
}